# Generated by Django 4.1.2 on 2024-07-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmoss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id_casa', models.AutoField(db_column='idcasa', primary_key=True, serialize=False)),
                ('Ubicacion', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible')], default='disponible', max_length=15)),
                ('imagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
