# Generated by Django 5.0.2 on 2024-07-03 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmoss', '0002_casa_delete_alumno_delete_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='Ubicacion',
            new_name='ubicacion',
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_arriendo', models.DateField(auto_now_add=True)),
                ('dias_arriendo', models.PositiveIntegerField()),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmoss.casa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
